### ISSUE TITLE
Unable to `dev` Makie

### ISSUE THREAD

**Issue by TomRottier** [MakieOrg/Makie.jl#5091]
I think this is because the path for `ComputePipeline` is wrong in Makie's [Project.toml](https://github.com/MakieOrg/Makie.jl/blob/0bdf2f2e5a87557fa8cb1198354a0dae7ec7264b/Makie/Project.toml#L68C1-L69C48)

```toml
[sources]
ComputePipeline = {path = "./ComputePipeline/"}
```

where it should be one level up, although `ComputePipeline` is registered so I'm not sure this is needed.
